### PR TITLE
Feature/restaurant

### PR DESCRIPTION
**Pull request by aracelicaes**
TSE,
TA simple Restaurant Homepage to practice DOM manipulation through dynamic rendering, the use of event listeners, and webpack to divide each content part into modules and reduce the load time of the site.

When you click on each navigation link "Home, Menu, About" you will see the page doesn't reload, but it'll render a different content each time. This is through DOM manipulation, resetting the DOM each time a link is clicked, and appending the proper and corresponding content to each link. I have made the requested changes from the previous TSE and the project is now complete. Looking forward to reading your feedback!

Ara Camarillo

### CODE REVIEW

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Invalid Submission :x: :disappointed: :stop_sign: 
## Hello @aracelicaes   :handshake: :handshake: :handshake: 

Thank you for submitting a code review request. And congratulations on that you have completed the restaurant page. However your code review request is marked as invalid due to the following reasons:

1. The submitted Pull Request is missing a descriptive readme file, kindly add it

Happy coding!!!
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Changes Required :red_circle:
To Highlight: :angel:

- It uses Webpack :+1: 
- All necessarily used packages are included in package.json :100: 
- Necessary run common commands are inside `scripts'. :1st_place_medal: 

To Improve :factory_worker: (REQUIRED)

- [x] Please, use **arrow** functions instead of the **function** keyword as you are using ES6. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/es6_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622983/))
- [x] It will be nice if you add instructions about how to use your project in your readme file. Example: how to build it, how to open it via browser, ... .

Nice to have:

- It will be nice if you add `start scripts` in your `package.json` .

That's it, you can submit another code review request after making these changes :recycle: :innocent:
With all my respect :pray:
Rindra Josia

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Ara Camarillo Estudillo** 
Good job with the improvements for this project :muscle:  :muscle:
Amazing work with the styling :clap: :clap: :clap:  
There are just a few details to improve before you can go ahead:

- [x] It appends HTML elements to the <div> with id=content when the page is loaded
- [x] It should have a main.js file that is built by webpack
- [x] The index.html links the main.js file
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Comment by aracelicaes** [comment]
>     * It appends HTML elements to the  with id=content when the page is loaded

|Can you please clear up the first requirement? it seems like it's cut. Also, I am linking it, I use the id = content and also on the same element, a class = theContent
So, it's the same thing. 

About the main.js it's called bundle.js it's the exact same thing. Please consider?

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Ara Camarillo Estudillo** 
Good job with the improvements for this project :muscle:  :muscle:
It meets most of the requirements :clap: :clap: :clap:  
Just one last detail to fix:

- [x] According to the instructions all the content should be added inside the div with id="content". Just move your footer and header inside the div since it should work as the parent element of all the content of the page.

 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Review by NtwaliHeritier — APPROVED** [review]
### **STATUS: APPROVED✔✔✔**

Hello @aracelicaes 
Great work implementing the required changes. 
You can merge the branches✔✔
Happy coding 💻💻

**Comment by aracelicaes** [comment]
Merging as per TSE approval.

**Pull request merged**
